---
- name: "Copy Logstash infrastructure template to the remote"
  template: src={{ item }}.j2 dest=/tmp/{{ item }}
  with_items:
  - logstash-service.yaml
  - logstash-dc.yaml

- name: "Create Logstash infrastructure template"
  shell: oc apply -f /tmp/{{ item }}
  with_items:
  - logstash-service.yaml
  - logstash-dc.yaml
