---
- name: Deploy Logstash
  hosts: nodes
  vars:
    ci_job_name: Interop-OSP_10-OCP_3.4-MLibVirt-HA-smoke-70e5f-stable-runtest
    time_range_start_at: now-1d/d
  roles:
  - role: logstash-job-openshift
    configs_dir: "{{ inventory_dir }}/../../logstash-configs/"
    logstash_project: phoebe-analytics-scripts-test
    kubeconfig: /home/emqiu/.kube/config
    job_name: job-1
